[theme]
# Azul institucional UdeG
primaryColor = "#004a87"
# Fondo de la barra lateral
backgroundColor = "#ffffff"
# Fondo secundario (gris claro)
secondaryBackgroundColor = "#f0f5f9"
# Color de texto principal
textColor = "#000000"
# Tipografía limpia
font = "sans serif"

[server]
# Optimización para que el logo cargue más rápido
enableCORS = false
